url: https://www.hometheatersaltlakecity.com
title: Home Theater Salt Lake City
phone: (385) 503-4456

google-analytics: G-BDDEXRNSZ3

category-list: [services]

# Fonts
font:
  # Body copy
  sans-serif-name: 'Open Sans'
  sans-serif: "https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;700&display=swap" 
  # Heading copy
  serif-name: 'Open Sans'
  serif: ""

# Privacy Policy and Terms of Service page
state: Utah

# Custom Navbar Colors
navbar-colors:
  bg: "#ffffff"
  menu-color: "#000000"
  menu-hover-color: "19495B"
  
# Custom button
btn-custom-primary:
  text-color: "#ffffff"
  bg: "#000000"
  border-color: "#000000"
  hover-text-color: "#ffffff"
  hover-bg: "#3f3f3f"
  hover-border-color: "#3f3f3f"

btn-custom-secondary:
  text-color: "#000000"
  bg: "#ffffff"
  border-color: "#ffffff"
  hover-text-color: "#000000"
  hover-bg: "#dddddd"
  hover-border-color: "#dddddd"

btn-border-radius: "4px"

# Call to action box bg color
cta:
  bg: "#000000"
  
# Form background color
form: 
  bg: "#ffffff"


# Local Business Schema
schema:
  # name: Same as title above
  image: ""
  # telephone: Same as phone above
  priceRange: "$$"
  address:
    city: "Salt Lake City"
    state: "Utah"
    country: "USA"
    postalCode: "84101"
  hours:
    dayOfWeek: "Monday-Saturday"
  # url: Same as url above
# End Schema